### ISSUE TITLE
Download/Start page OS and browser detection

### ISSUE THREAD

**Issue by fcheslack** [zotero/web-components#4]
selecting which client/connectors to recommend downloading

- [ ] async registration
- [ ] ease up registration confirmation
- [ ] expand to show all connectors on same page (?)
- [ ] easily updatable download urls without modifying react component

**Comment by dstillman** [comment]
The client download URL can default to a generic URL for the platform:

`https://www.zotero.org/download/standalone/dl?platform=<platform>`, where `<platform>` is one of `mac`, `win32`, `linux-i686`, `linux-x86_64`

This returns a 302 with a download link.

To show a more helpful URL to the user and let them download old versions more easily, we should probably grab the current update manifest from `https://www.zotero.org/download/standalone/manifests/release/updates-<platform>.json` and build a URL that includes the version, and then swap that in. I could then update the `dl` script to use a passed `version` parameter instead of the latest version.

There's also a download redirector for Firefox and Safari:

`https://www.zotero.org/download/connector/dl?browser=<browser>`, where `<browser>` is one of `firefox` or `safari` (not yet hooked up for Safari, but I'll do that)

I don't think we need to worry about swapping in version-based URLs for those, but we possibly do still want to get the current Firefox hash. I'm not sure if that's still necessary with messed-up connections for WebExtensions. (I don't even remember what the issue was, exactly. Custom CAs?) In any case, if we do this, the Firefox manifest is available here:

https://www.zotero.org/download/connector/firefox/updates.json

(If we do that, we should swap in the URL too to make sure they're getting the same version.)

**Comment by fcheslack** [comment]
closed by https://github.com/zotero/web-components/commit/2e4c47745e5861a4990a0ef39329e3d95d436c8a among others
